AppBundle\Entity\MaternityLeave:
    type: entity
    table: maternity_leave
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        employeeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: employee_id
        dateStart:
            type: datetime
            nullable: false
            column: date_start
        dateEnd:
            type: datetime
            nullable: true
            column: date_end
    lifecycleCallbacks: {  }
