AppBundle\Entity\Shift:
    type: entity
    table: shift
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        backgroundColor:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ffffff
            column: background_color
        color:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: '000000'
    lifecycleCallbacks: {  }
