AppBundle\Entity\TeamShift:
    type: entity
    table: team_shift
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        teamId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: team_id
        shiftId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: shift_id
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
